"""Frequency windows for the 3D reflectivity map (analogue of refl_map.py::_windows).

In 2D (alpha = 0, n^u = 1) the paper's bands omega in [q, q+1] are exactly the intervals between
consecutive Rayleigh (Wood) frequencies of the upper layer, n^u omega = |alpha + p|; the delta
series of every quantity has a branch point there, so each band gets its own HOPS/AWE expansion
with |delta| < sigma / (2q + 1)   (paper eqs. (28)-(30)).

For a doubly periodic grating the Rayleigh frequencies are
        n omega = |(alpha + p, beta + q)|,   (p, q) in Z^2,
e.g. 1, sqrt 2, 2, sqrt 5, sqrt 8, 3, sqrt 10, ... for normal incidence, so the 3D analogue of a
"band" is the interval between two consecutive such values.  Every window [w_a, w_b] is expanded
about its midpoint omega_bar = (w_a + w_b)/2 with |delta| <= sigma (w_b - w_a) / (w_b + w_a)
(identical to eq. (30) for [q, q+1]).
  mode 'paper' : cut at the upper-layer Rayleigh frequencies only (the 2D default)
  mode 'joint' : also cut at the lower-layer ones when n^w is real (lossless), as refl_map --windows joint
  max_delta    : further geometric split so that |delta| <= max_delta
  lattice      : None = all orders (p, q) in Z^2 (the analogue of the 2D bands); or the orders the
                 profile can excite (profile_lattice) -> far fewer cuts for e.g. cos(4x)cos(4y)
"""
import numpy as np


def _lattice(kmax, period, n_modes):
    if n_modes == 1:                      # invariant direction: only the zero mode exists
        return np.zeros(1)
    j = int(kmax * period / (2 * np.pi)) + 3
    return (2 * np.pi / period) * np.arange(-j, j + 1)


def profile_lattice(f, kmax, tol=1e-10, dx_period=2 * np.pi, dy_period=2 * np.pi):
    """Wavenumbers (p, q) of the diffraction orders a profile f can actually excite at normal
    incidence: the integer lattice generated by the Fourier modes of f (|f^_pq| > tol max|f^|),
    restricted to |(p, q)| <= kmax.  E.g. cos(4x)cos(4y) excites only (4a, 4b) with a = b mod 2,
    so its first Rayleigh anomaly is at |(4, 4)| = 5.66 instead of 1."""
    Nx, Ny = f.shape
    fh = np.fft.fft2(f)
    idx = np.argwhere(np.abs(fh) > tol * np.abs(fh).max())
    kx = np.fft.fftfreq(Nx, 1.0 / Nx).astype(int)
    ky = np.fft.fftfreq(Ny, 1.0 / Ny).astype(int)
    gens = {(int(kx[i]), int(ky[j])) for i, j in idx if (kx[i], ky[j]) != (0, 0)}
    gens |= {(-a, -b) for a, b in gens}
    R = int(np.ceil(kmax)) + 1
    pts, frontier = {(0, 0)}, [(0, 0)]
    while frontier:
        new = []
        for a, b in frontier:
            for g1, g2 in gens:
                c = (a + g1, b + g2)
                if abs(c[0]) <= R and abs(c[1]) <= R and c not in pts:
                    pts.add(c)
                    new.append(c)
        frontier = new
    P = np.array(sorted(pts), dtype=float)
    return P[:, 0] * (2 * np.pi / dx_period), P[:, 1] * (2 * np.pi / dy_period)


def rayleigh_3d(n_re, alpha, beta, lo, hi, dx_period=2 * np.pi, dy_period=2 * np.pi, Nx=2, Ny=2,
                angle=None, lattice=None):
    """Sorted Rayleigh frequencies in the open interval (lo, hi).

    angle=None       : fixed lateral wavenumbers (alpha, beta):  n omega = |(alpha + p, beta + q)|
    angle=(a_, b_)   : fixed incidence angle, alpha = a_ omega, beta = b_ omega
                       (a_ = n^u sin(theta) cos(phi), b_ = n^u sin(theta) sin(phi)):
                       (n^2 - a_^2 - b_^2) omega^2 - 2 (a_ p + b_ q) omega - (p^2 + q^2) = 0.
    Nx = 1 / Ny = 1 marks a direction in which the grating is invariant (only p = 0 / q = 0).
    """
    if n_re <= 0:
        return []
    kmax = hi * n_re + abs(alpha) + abs(beta) + 2
    if lattice is not None:              # explicit list of excitable orders (profile_lattice)
        P, Q = lattice
    else:
        P = _lattice(kmax, dx_period, Nx)[:, None]
        Q = _lattice(kmax, dy_period, Ny)[None, :]
    if angle is None:
        w = np.hypot(alpha + P, beta + Q).ravel() / n_re
    else:
        a_, b_ = angle
        A = n_re ** 2 - a_ ** 2 - b_ ** 2
        B = -2 * (a_ * P + b_ * Q)
        C = -(P ** 2 + Q ** 2)
        disc = np.sqrt(np.maximum(B ** 2 - 4 * A * C, 0.0))
        w = np.concatenate([((-B + disc) / (2 * A)).ravel(), ((-B - disc) / (2 * A)).ravel()])
    w = np.unique(np.round(w[(w > lo) & (w < hi)], 12))
    return list(w)


def make_windows(omega_lo, omega_hi, n_u_re, n_w, alpha, beta, sigma=0.99, mode='paper', min_width=0.02,
                 max_delta=None, dx_period=2 * np.pi, dy_period=2 * np.pi, omega_min_frac=0.02, Nx=2, Ny=2,
                 angle=None, lattice=None):
    """List of (key, omega_bar, delta_max, (w_a, w_b)) covering [omega_lo, omega_hi].
    Windows narrower than min_width (relative, (w_b - w_a)/omega_bar) are dropped (slivers between
    two nearly coincident anomalies; the 2D code does the same)."""
    lo = max(omega_lo, omega_min_frac * omega_hi)
    kw = dict(dx_period=dx_period, dy_period=dy_period, Nx=Nx, Ny=Ny, angle=angle, lattice=lattice)
    cuts = rayleigh_3d(n_u_re, alpha, beta, lo, omega_hi, **kw)
    if mode == 'joint' and abs(np.imag(n_w)) < 1e-3 * abs(n_w) and np.real(n_w) > 0:
        cuts += rayleigh_3d(np.real(n_w), alpha, beta, lo, omega_hi, **kw)
    edges = [lo] + sorted(set(np.round(cuts, 12))) + [omega_hi]
    segs = [(a, b) for a, b in zip(edges[:-1], edges[1:]) if (b - a) >= min_width * 0.5 * (a + b)]
    out = []
    for a, b in segs:
        pieces = [a, b]
        if max_delta:
            md = max_delta / sigma
            k = max(1, int(np.ceil(np.log(b / a) / np.log((1 + md) / (1 - md)))))
            pieces = [a] + list(a * (b / a) ** (np.arange(1, k + 1) / k))
        for c, e in zip(pieces[:-1], pieces[1:]):
            ob = 0.5 * (c + e)
            out.append((f'w{len(out):02d}', ob, sigma * (e - c) / (e + c), (c, e)))
    return out
